/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaseRouteImport } from './routes/base'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaseIndexRouteImport } from './routes/base.index'
import { Route as BaseCategoriaEspecializacaoRouteImport } from './routes/base.$categoria.$especializacao'

const BaseRoute = BaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRoute,
} as any)
const BaseCategoriaEspecializacaoRoute =
  BaseCategoriaEspecializacaoRouteImport.update({
    id: '/$categoria/$especializacao',
    path: '/$categoria/$especializacao',
    getParentRoute: () => BaseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base': typeof BaseRouteWithChildren
  '/base/': typeof BaseIndexRoute
  '/base/$categoria/$especializacao': typeof BaseCategoriaEspecializacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base': typeof BaseIndexRoute
  '/base/$categoria/$especializacao': typeof BaseCategoriaEspecializacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base': typeof BaseRouteWithChildren
  '/base/': typeof BaseIndexRoute
  '/base/$categoria/$especializacao': typeof BaseCategoriaEspecializacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/base' | '/base/' | '/base/$categoria/$especializacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/base' | '/base/$categoria/$especializacao'
  id: '__root__' | '/' | '/base' | '/base/' | '/base/$categoria/$especializacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaseRoute: typeof BaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/base': {
      id: '/base'
      path: '/base'
      fullPath: '/base'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/': {
      id: '/base/'
      path: '/'
      fullPath: '/base/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/base/$categoria/$especializacao': {
      id: '/base/$categoria/$especializacao'
      path: '/$categoria/$especializacao'
      fullPath: '/base/$categoria/$especializacao'
      preLoaderRoute: typeof BaseCategoriaEspecializacaoRouteImport
      parentRoute: typeof BaseRoute
    }
  }
}

interface BaseRouteChildren {
  BaseIndexRoute: typeof BaseIndexRoute
  BaseCategoriaEspecializacaoRoute: typeof BaseCategoriaEspecializacaoRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseIndexRoute: BaseIndexRoute,
  BaseCategoriaEspecializacaoRoute: BaseCategoriaEspecializacaoRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaseRoute: BaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
